mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from books import views
from django.contrib import auth
from mysite.views import hello
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello),
    #use for login and logout 
    (r'^accounts/login/$',login),
    (r'^accounts/logout/$',logout),

    (r'^logout/$',views.logout_view),
    (r'^login_view/$',views.login_view),#custom login process
    #('^hello/$', hello),
    (r'^search-form/$', views.search_form),
    (r'^search/$',views.search),
    (r'^contact/$',views.contact),
    url(r'^books/$',views.getBooks),

    url(r'^updateBook/(\d+)/$',views.updateBook,name='updateBook'),
    (r'^getBookById/(\d+)/$', views.getBookById),

    #use for user register
    (r'^register/$',views.register),
    url(r'^getArticle/$',views.getArticle),
    url(r'^updateArticle/(\d+)/$',views.updateArticle,name='updateArticle'),
    
)

books/models.py
from django.db import models
from django.db import connection,models

class UserProfileManager(models.Manager):
    def getUserProfile(self,name):
      cursor = connection.cursor()
      cursor.execute("select username,website,nickname from auth_user,books_publisher,books_info where books_publisher.id = auth_user.id and books_info.id = auth_user.id")
      return [row for row in cursor.fetchone()]

class BooksLogManager(models.Manager):
    """docstring for UserLogManager"""
    def getUserProfile(self,name):
      cursor = connection.cursor()
      cursor.execute("select username,log_info from auth_user,books_log where auth_user.id = books_log.id")
      return [row for row in cursor.fetchone()]
                    
class CCLogManager(models.Manager):
    """docstring for UserLogManager"""
    def getUserProfile(self,name):
      cursor = connection.cursor()
      cursor.execute("select username,log_info from auth_user,cc_log where auth_user.id = cc_log.id")
      return [row for row in cursor.fetchone()]    

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
    def __unicode__(self):
      return self.name

class Author(models.Model):
    "author models is beginning..."
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    def __unicode__(self):
      return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    # num_page = models.IntegerField(blank=True, null=True)
    def __unicode__(self):
      return self.title

class UserProfile(models.Model):
    nickname = models.CharField(max_length=50)
    username = models.CharField(max_length=30)
    website = models.CharField(max_length=200)
    objects = UserProfileManager()
    objects = models.Manager()
    upf_objects = UserProfileManager()
    bl_objects = BooksLogManager()
    ccl_objects = CCLogManager()


class Article(models.Model):
    headline = models.CharField(max_length=200, null=True, blank=True,
      help_text="Use puns liberally")
    content = models.TextField()

books/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.forms.extras.widgets import Select
from books.models import *
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS



BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
FAVORITE_COLORS_CHOICES = (('blue', 'Blue'),
                            ('green', 'Green'),
                            ('black', 'Black'))
MONTHS = {
    1:('jan'), 2:('feb'), 3:('mar'), 4:('apr'),
    5:('may'), 6:('jun'), 7:('jul'), 8:('aug'),
    9:('sep'), 10:('oct'), 11:('nov'), 12:('dec')
}
 
YEAR_IN_SCHOOL_CHOICES = (
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior'),
) 

class ContactForm(forms.Form):
   subject = forms.CharField(required=False, max_length=5, help_text='100 characters max.')
   email = forms.EmailField(error_messages={'required': '你这个无名人士.....'},help_text="请输入邮件格式")
   message = forms.CharField()
   # contactType = forms.CharField(widget=SelectDateWidget(years=BIRTH_YEAR_CHOICES))
   contactDay = forms.CharField(widget=SelectDateWidget(years=BIRTH_YEAR_CHOICES,months=MONTHS))
   contactTime = forms.TimeField()
   contactTpye = forms.ChoiceField(choices=YEAR_IN_SCHOOL_CHOICES)
   webUrl = forms.URLField()

   def clean_message(self):
       message = self.cleaned_data['message']
       num_words = len(message.split())
       if num_words < 4:
           raise forms.ValidationError("请输入超过4个字符")
       return message 



class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'email']

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'authors','publisher','publication_date']



class ArticleForm(ModelForm):
    class Meta:
    	model = Article
        fields = ['headline', 'content']
        # error_messages = {
        #     NON_FIELD_ERRORS: {
        #         'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
        #     }
        # }        

books/views.py
from django.shortcuts import render_to_response,get_object_or_404
from django.http import HttpResponse
from books.models import Book
from books.models import Article
from django.core.mail import send_mail
from books.forms import ContactForm
from books.forms import ArticleForm
from books.forms import BookForm
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt



def UploadImage(request):
    '''UploadImage function do not work!!!'''
    if request.method == 'POST':
        content = request.FILES['ImageField']
        try:
            img = Image.open(content)
            img.thumbnail((500,500),Image.ANTIALIAS)
            img.save("abv.png","jpg")
        except Exception,e:
            return HttpResponse("Error %s"%e)
        return HttpResponse("ok")
    return HttpResponse("error")


def search_form(request):
    return render_to_response('search_form.html')

def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        books = Book.objects.filter(title__icontains=q)
        return render_to_response('search_results.html',
        {'books': books, 'query': q})
    else:
        return render_to_response('search_form.html', {'error': True})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
           cd = form.cleaned_data
           # send_mail(
           #  cd['subject'],
           #  cd['message'],
           #  cd.get('email', 'noreply@example.com'),
           #  ['siteowner@example.com'],
           # )
           return HttpResponseRedirect("/books")
        else:
            return render_to_response('contact_form.html', {'form': form},context_instance=RequestContext(request))
    else:
        form = ContactForm(initial={'subject': 'I love your site!'})
        return render_to_response('contact_form.html', {'form': form},context_instance=RequestContext(request))


@login_required
def getBooks(request):
    # if not request.user.is_authenticated():
    #       return HttpResponseRedirect('/accounts/login/?next=%s' % request.path)
    books = Book.objects.all()
    return render_to_response('book_list.html',{"book_list":books},context_instance=RequestContext(request))
    # return render_to_response('book_list.html',{"book_list":books})

def getBookById(request,id):
    book = get_object_or_404(Book,pk=int(id))
    return render_to_response('book_detail.html',{"book":book},context_instance=RequestContext(request))


def register(request):
    '''user register'''
    if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
        new_user = form.save()
        return HttpResponseRedirect("/books")
    else:
      form = UserCreationForm()
    return render_to_response("registration/register.html", {'form': form},context_instance=RequestContext(request))


def logout_view(request):
    auth.logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/accounts/login/")

@csrf_exempt
def login_view(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = auth.authenticate(username=username,password=password)
    if user is not None and user.is_active:
      auth.login(request, user)
      return  HttpResponseRedirect("/books")
    else:
      return HttpResponseRedirect("/accounts/login/")

def updateBook(request,id):
    book = get_object_or_404(Book,pk=int(id))
    if request.method=="POST":
        form = BookForm(request.POST,instance=book)
        if form.is_valid():
          form.save()
          return HttpResponseRedirect("/books")
        else:
          render_to_response('book_detail.html',{"form":BookForm(instance=book)},context_instance=RequestContext(request))  
    return render_to_response('book_detail.html',{"form":BookForm(instance=book)},context_instance=RequestContext(request))



def getArticle(request):
    # if not request.user.is_authenticated():
    #       return HttpResponseRedirect('/accounts/login/?next=%s' % request.path)
    articles = Article.objects.all()
    return render_to_response('article_list.html',{"article_list":articles},context_instance=RequestContext(request))
 


def updateArticle(request,id):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
           form.cleaned_data
           # cd.save()
           form.save()
           return HttpResponseRedirect("/getArticle")
        else:
            return render_to_response('article_form.html', {'form': form},context_instance=RequestContext(request))
    else:
        form = ArticleForm(initial={'headline': 'pls write your name !'})
        return render_to_response('article_form.html', {'form': form},context_instance=RequestContext(request))

books/templates/article_detail.html
<html>
      <head>
       <title>book detail</title>
      </head>
      <style type="text/css">
         ul.errorlist {
           margin: 0;
           padding: 0;
         }
         .errorlist li {
           background‐ color: red;
           color: red;
           display: block;
           font‐ size: 10px;
           margin: 0 0 3px;
           padding: 4px 5px;
         }
      </style>

      <body>
             <h1>add article</h1>
               {% if form.errors %}
                <p style="color: red;">
                   Please correct the error{{ form.errors|pluralize }} below.
                </p>
             {% endif %}
             <form action="" method="post">
                 {% csrf_token %}
                 <div class="field">
                     {{ form.headline.errors }}
                     <label for="id_headline">headline:</label>
                     {{ form.headline }}
                     {{ form.headline.help_text }}
                 </div>
                 <div class="field">
                     {{ form.content.errors }}
                     <label for="id_content">content:</label>
                     {{ form.content }}
                 </div>
                 <input type="submit" value="Submit">
             </form>
      </body>
</html

books/templates/article_form.html
<html>
      <head>
       <title>article</title>
      </head>
      <style type="text/css">
         ul.errorlist {
           margin: 0;
           padding: 0;
         }
         .errorlist li {
           background‐ color: red;
           color: red;
           display: block;
           font‐ size: 10px;
           margin: 0 0 3px;
           padding: 4px 5px;
         }
      </style>

      <body>
             <h1>add article</h1>
               {% if form.errors %}
                <p style="color: red;">
                   Please correct the error{{ form.errors|pluralize }} below.
                </p>
             {% endif %}
             <form action="" method="post">
                 {% csrf_token %}
                  {{ form.id}}
                 <div class="field">
                     {{ form.headline.errors }}
                     <label for="id_headline">headline:</label>
                     {{ form.headline }}
                     {{ form.headline.help_text }}
                 </div>
                 <div class="field">
                     {{ form.content.errors }}
                     <label for="id_content">content:</label>
                     {{ form.content }}
                 </div>
                 <input type="submit" value="Submit">
             </form>
      </body>
</html

books/templates/article_list.html
 
   {% if article_list %}
 <p>Found {{ article_list|length }} article{{ article_list|pluralize }}.</p>
 <ul>
 {% for article in article_list %}
 <li>{{ article.headline }} <a href='{% url "updateArticle" article.id %}'>修改</a></li>
 
 {% endfor %}
 </ul>

{% else %}
 <p>No articles.</p>
{% endif %}
 

-----------------------------------------
 <a href="/logout">logout</a>

books/templates/book_detail.html
<html>
      <head>
       <title>book detail</title>
      </head>
      <style type="text/css">
         ul.errorlist {
           margin: 0;
           padding: 0;
         }
         .errorlist li {
           background‐ color: red;
           color: red;
           display: block;
           font‐ size: 10px;
           margin: 0 0 3px;
           padding: 4px 5px;
         }
      </style>

      <body>
             <h1>add article</h1>
               {% if form.errors %}
                <p style="color: red;">
                   Please correct the error{{ form.errors|pluralize }} below.
                </p>
             {% endif %}
             <form action="" method="post">
                 {% csrf_token %}
                 <div class="field">
                     {{ form.title.errors }}
                     <label for="id_title">title:</label>
                     {{ form.title }}
                     {{ form.title.help_text }}
                 </div>
                 <div class="field">
                     {{ form.publication_date.errors }}
                     <label for="id_publication_date">publication_date:</label>
                     {{ form.publication_date }}
                 </div>
                 <div class="field">
                     {{ form.authors.errors }}
                     <label for="id_authors">authors:</label>
                     {{ form.authors }}
                 </div>
                 <div class="field">
                     {{ form.publisher.errors }}
                     <label for="id_publisher">publisher:</label>
                     {{ form.publisher }}
                 </div>

                 <input type="submit" value="Submit">
             </form>
      </body>
</html

books/templates/book_list.html
{% load pagination_tags %}
{% autopaginate book_list 5 %}
   {% if book_list %}
 <p>Found {{ book_list|length }} book{{ book_list|pluralize }}.</p>
 <ul>
 {% for book in book_list %}
 <li>{{ book.title }} <a href='{% url "updateBook" book.id %}'>修改</a></li>
 
 {% endfor %}
 </ul>

{% else %}
 <p>No books.</p>
{% endif %}
 {% paginate %}

-----------------------------------------
 <a href="/logout">logout</a>

books/templates/contact_form.html
<html>
      <head>
       <title>Contact us</title>
      </head>
      <style type="text/css">
         ul.errorlist {
           margin: 0;
           padding: 0;
         }
         .errorlist li {
           background‐ color: red;
           color: red;
           display: block;
           font‐ size: 10px;
           margin: 0 0 3px;
           padding: 4px 5px;
         }
      </style>

      <body>
             <h1>Contact us</h1>
               {% if form.errors %}
                <p style="color: red;">
                   Please correct the error{{ form.errors|pluralize }} below.
                </p>
             {% endif %}
             <form action="" method="post">
                 {% csrf_token %}
                 <div class="field">
                     {{ form.subject.errors }}
                     <label for="id_subject">Subject:</label>
                     {{ form.subject }}
                     {{ form.subject.help_text }}
                 </div>
                 <div class="field">
                     {{ form.email.errors }}
                     <label for="id_email">Your e‐mail address:</label>
                     {{ form.email }}
                     {{ form.email.help_text }}
                 </div>
                 <div class="field">
                     {{ form.message.errors }}
                     <label for="id_message">Message:</label>
                     {{ form.message }}
                 </div>
                 <div class="field">
                     {{ form.contactDay.errors }}
                     <label for="id_contactDay">contact day:</label>
                     {{ form.contactDay }}
                 </div>
                 <div class="field">
                     {{ form.contactTime.errors }}
                     <label for="id_contactTime">contact Time:</label>
                     {{ form.contactTime }}
                 </div>
                 <div class="field">
                     {{ form.contactTpye.errors }}
                     <label for="id_contactType">contact Type:</label>
                     {{ form.contactTpye }}
                 </div>
                 <div class="field">
                     {{ form.webUrl.errors }}
                     <label for="id_webUrl">web Url:</label>
                     {{ form.webUrl }}
                 </div>
                 <input type="submit" value="Submit">
             </form>
      </body>
</html

books/templates/search_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
     {% if error %}
        <p style="color: red;">Please submit a search term 20 characters or shorter.</p>
    {% endif %}
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

books/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>
{% if books %}
 <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
 <ul>
 {% for book in books %}
 <li>{{ book.title }}</li>
 {% endfor %}
 </ul>
{% else %}
 <p>No books matched your search criteria.</p>
{% endif %}